Rails.application.routes.draw do
   root to: "users#index"
   get "/users", to: "users#index", as: "users"
   get "/users/new", to: "users#new", as: "new_user"
   post "/users", to: "users#create"
   get "/users/:id", to: "users#show", as: "user"
   get "/login", to: "sessions#new", as: "login"
   post "/sessions", to: "sessions#create"
   get "/logout", to: "sessions#destroy"
   get "users/:id/edit", to: "users#edit", as:"user_edit"
   patch "/users/:id", to: "users#update", as:"user_update"
   get "/libraries", to: "libraries#index", as: "libraries"
   get "/libraries/new", to: "libraries#new", as: "new_library"
   post "/libraries", to: "libraries#create"
   get "/libraries/:id", to: "libraries#show", as: "library"
   get "/users/:user_id/libraries", to: "library_users#index", as: "user_libraries"
   post "/libraries/:library_id/users", to: "library_users#create", as: "library_users"
   get "/libraries/:library_id/users", to: "library_users#show", as: "library_users_show"
   get "/libraries/:library_id/edit", to: "libraries#edit", as: "library_edit"
   patch "/libraries/:library_id", to: "libraries#update"
   delete "/libraries/:library_id", to: "libraries#destroy"
   get "/libraries/:library_id/books/new", to: "library_books#new", as: "new_book"
   get "libraries/:library_id/books/:book_id/edit", to: "library_books#edit", as:"edit_book"
   get "/libraries/:library_id/books/:book_id", to: "library_books#show", as: "library_book"
   get "/libraries/:library_id/books", to: "library_books#index", as:"library_books"
   get "/libraries/:library_id/books/:book_id", to: "library_books#show", as:"book"
   post "/libraries/:library_id/books", to: "library_books#create"
   patch "libraries/:library_id/books/:book_id", to: "library_books#update"
   delete "/libraries/:library_id/books/:book_id", to: "library_books#destroy"
end
